### ISSUE TITLE
rundummy: No such file or directory: u'tmp/config.yaml'

### ISSUE THREAD

**Issue by jorisbontje** [HydraChain/hydrachain#3]
```
$ mkdir tmp
$ hydrachain -d tmp rundummy --num_validators=3 --node_num=0 --seed=42
No handlers could be found for logger "eth.pow"

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO:app	using data in path=tmp
INFO:config	loading config path=tmp
Traceback (most recent call last):
  File "/Users/mids/.virtualenvs/hydrachain/bin/hydrachain", line 9, in <module>
    load_entry_point('hydrachain==0.0.1', 'console_scripts', 'hydrachain')()
  File "/Users/mids/Projects/ethereum/hydrachain/hydrachain/app.py", line 148, in app
    pyethapp_app.app()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.1-py2.7.egg/pyethapp/app.py", line 85, in app
    config = konfig.load_config(data_dir)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.1-py2.7.egg/pyethapp/config.py", line 99, in load_config
    _fix_accounts(path)  # FIXME
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.1-py2.7.egg/pyethapp/config.py", line 81, in _fix_accounts
    config = yaml.load(open(path))
IOError: [Errno 2] No such file or directory: u'tmp/config.yaml'
```

After this the `config.yaml` file is created, so a 2nd run succeeds. However I would expect the first run not to crash given an empty data dir.

**Comment by heikoheiko** [comment]
fixed in pyethapp-1.0.2

**Comment by jorisbontje** [comment]
Not fixed for me with 63229e04a461b721c51e2690cedfed1d30ef0dbd and pyethapp-1.0.2:

```
$ pip freeze|grep pyethapp
pyethapp==1.0.2
$ hydrachain -d datadir rundummy --num_validators=3 --node_num=0 --seed=42
No handlers could be found for logger "eth.pow"

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO:app	using data in path=datadir
INFO:config	loading config path=datadir
Traceback (most recent call last):
  File "/Users/mids/.virtualenvs/hydrachain/bin/hydrachain", line 9, in <module>
    load_entry_point('hydrachain==0.0.1', 'console_scripts', 'hydrachain')()
  File "/Users/mids/Projects/ethereum/hydrachain/hydrachain/app.py", line 148, in app
    pyethapp_app.app()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.2-py2.7.egg/pyethapp/app.py", line 88, in app
    config = konfig.load_config(data_dir)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.2-py2.7.egg/pyethapp/config.py", line 99, in load_config
    _fix_accounts(path)  # FIXME
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.2-py2.7.egg/pyethapp/config.py", line 81, in _fix_accounts
    config = yaml.load(open(path))
IOError: [Errno 2] No such file or directory: u'datadir/config.yaml'
```

**Comment by jorisbontje** [comment]
Ah, this only happens if `datadir` exists, but is empty. If it doesn't exist, then it will be created, with the `config.yaml` in it.

**Comment by heikoheiko** [comment]
created an issue https://github.com/ethereum/pyethapp/issues/58
